name: Update README languages card

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      USERNAME: ${{ github.repository_owner }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Generate most used languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ env.USERNAME }}&langs_count=6&theme=dark_github
          path: profile/languages.svg
          token: ${{ env.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "chore(readme): update profile readme cards" || exit 0
          git push
